{% set version = "0.4.0" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ggstatsplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstatsplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstatsplot/ggstatsplot_{{ version }}.tar.gz
  sha256: ef284e8528940c93f5e60a7524ff142799c2dc6be91b918fbfef95bf2ecc1e06

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base >=3.6
    - r-broomextra >=0.0.6
    - r-cowplot >=1.0.0
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-ggextra >=0.9
    - r-ggcorrplot >=0.1.3
    - r-ggplot2 >=3.3.0
    - r-ggrepel >=0.8.1
    - r-ggsignif >=0.6.0
    - r-groupedstats >=0.1.0
    - r-ipmisc
    - r-pairwisecomparisons >=0.1.2
    - r-paletteer >=1.0.0
    - r-purrr >=0.3.3
    - r-rlang >=0.4.2
    - r-statsexpressions >=0.1.3
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0
    - r-wrs2 >=1.0_0
  run:
    - r-base >=3.6
    - r-broomextra >=0.0.6
    - r-cowplot >=1.0.0
    - r-dplyr >=0.8.3
    - r-forcats >=0.4.0
    - r-ggextra >=0.9
    - r-ggcorrplot >=0.1.3
    - r-ggplot2 >=3.3.0
    - r-ggrepel >=0.8.1
    - r-ggsignif >=0.6.0
    - r-groupedstats >=0.1.0
    - r-ipmisc
    - r-pairwisecomparisons >=0.1.2
    - r-paletteer >=1.0.0
    - r-purrr >=0.3.3
    - r-rlang >=0.4.2
    - r-statsexpressions >=0.1.3
    - r-tibble >=2.1.3
    - r-tidyr >=1.0.0
    - r-wrs2 >=1.0_0

test:
  commands:
    - $R -e "library('ggstatsplot')"           # [not win]
    - "\"%R%\" -e \"library('ggstatsplot')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/ggstatsplot/, https://github.com/IndrajeetPatil/ggstatsplot
  license: GPL-3
  summary: "Extension of 'ggplot2', 'ggstatsplot' creates graphics with details from statistical tests included in the plots themselves. It is targeted primarily\
    \ at behavioral sciences community to provide a one-line code to generate information-rich plots for statistical analysis of continuous (violin plots, scatterplots,\
    \ histograms, dot plots, dot-and-whisker plots) or categorical (pie and bar charts) data. Currently, it supports only the most common types of statistical tests:\
    \ parametric, nonparametric, robust, and bayesian versions of t-test/anova, correlation analyses, contingency table analysis, and regression analyses."
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Type: Package
# Package: ggstatsplot
# Title: 'ggplot2' Based Plots with Statistical Details
# Version: 0.1.2
# Authors@R:  c(person(given = "Indrajeet", family = "Patil", role = c("cre", "aut", "ctb"), email = "patilindrajeet.science@gmail.com", comment = c(ORCID = "0000-0003-1995-6531")), person(given = "Chuck", family = "Powell", role = "ctb", email = "ibecav@gmail.com", comment = c(ORCID = "0000-0002-3606-2188")))
# Maintainer: Indrajeet Patil <patilindrajeet.science@gmail.com>
# Description: Extension of 'ggplot2', 'ggstatsplot' creates graphics with details from statistical tests included in the plots themselves. It is targeted primarily at behavioral sciences community to provide a one-line code to generate information-rich plots for statistical analysis of continuous (violin plots, scatterplots, histograms, dot plots, dot-and-whisker plots) or categorical (pie and bar charts) data. Currently, it supports only the most common types of statistical tests: parametric, nonparametric, robust, and bayesian versions of t-test/anova, correlation analyses, contingency table analysis, and regression analyses.
# License: GPL-3 | file LICENSE
# URL: https://indrajeetpatil.github.io/ggstatsplot/, https://github.com/IndrajeetPatil/ggstatsplot
# BugReports: https://github.com/IndrajeetPatil/ggstatsplot/issues
# Depends: R (>= 3.5.0)
# Imports: broomExtra (>= 0.0.5), cowplot (>= 1.0.0), crayon (>= 1.3.4), dplyr (>= 0.8.3), forcats (>= 0.4.0), ggcorrplot (>= 0.1.3), ggExtra (>= 0.9), ggplot2 (>= 3.2.1), ggrepel (>= 0.8.1), ggsignif (>= 0.6.0), grid, groupedstats (>= 0.0.9), insight (>= 0.5.0), metaBMA (>= 0.6.1), metafor (>= 2.1-0), pairwiseComparisons (>= 0.1.1), paletteer (>= 0.2.1), psych (>= 1.8.12), purrr (>= 0.3.2), rlang (>= 0.4.0), scales (>= 1.0.0), sjstats (>= 0.17.6), stats, statsExpressions (>= 0.1.1), tibble (>= 2.1.3), tidyr (>= 1.0.0), WRS2
# Suggests: broom, broom.mixed, jmv, knitr, lme4, MASS, MCMCglmm, ordinal, rmarkdown, spelling, stringr, survival, testthat
# VignetteBuilder: knitr
# Encoding: UTF-8
# Language: en-US
# LazyData: true
# RoxygenNote: 6.1.99.9000
# NeedsCompilation: no
# Packaged: 2019-09-17 10:01:41 UTC; inp099
# Author: Indrajeet Patil [cre, aut, ctb] (<https://orcid.org/0000-0003-1995-6531>), Chuck Powell [ctb] (<https://orcid.org/0000-0002-3606-2188>)
# Repository: CRAN
# Date/Publication: 2019-09-17 10:40:02 UTC
