{% set version = "0.13.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-ggstatsplot
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ggstatsplot_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ggstatsplot/ggstatsplot_{{ version }}.tar.gz
  sha256: 0ecfc1b939a0648bb31f79a2380cf8f6b1c3094b6e4545135838fcc10d761463

build:
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-correlation >=0.8.7
    - r-datawizard >=1.1.0
    - r-dplyr >=1.1.4
    - r-ggcorrplot >=0.1.4.1
    - r-ggplot2 >=3.5.2
    - r-ggrepel >=0.9.6
    - r-ggside >=0.3.1
    - r-ggsignif >=0.6.4
    - r-glue >=1.8.0
    - r-insight >=1.2.0
    - r-paletteer >=1.6.0
    - r-parameters >=0.25.0
    - r-patchwork >=1.3.0
    - r-performance >=0.13.0
    - r-purrr >=1.0.4
    - r-rlang >=1.1.6
    - r-statsexpressions >=1.7.0
    - r-tidyr >=1.3.1
  run:
    - r-base
    - r-correlation >=0.8.7
    - r-datawizard >=1.1.0
    - r-dplyr >=1.1.4
    - r-ggcorrplot >=0.1.4.1
    - r-ggplot2 >=3.5.2
    - r-ggrepel >=0.9.6
    - r-ggside >=0.3.1
    - r-ggsignif >=0.6.4
    - r-glue >=1.8.0
    - r-insight >=1.2.0
    - r-paletteer >=1.6.0
    - r-parameters >=0.25.0
    - r-patchwork >=1.3.0
    - r-performance >=0.13.0
    - r-purrr >=1.0.4
    - r-rlang >=1.1.6
    - r-statsexpressions >=1.7.0
    - r-tidyr >=1.3.1

test:
  commands:
    - $R -e "library('ggstatsplot')"           # [not win]
    - "\"%R%\" -e \"library('ggstatsplot')\""  # [win]

about:
  home: https://indrajeetpatil.github.io/ggstatsplot/
  dev_url: https://github.com/IndrajeetPatil/ggstatsplot
  license: MIT
  summary: "Extension of 'ggplot2', 'ggstatsplot' creates graphics with details from statistical tests included in the plots themselves. It provides an easier API to generate information-rich plots for statistical analysis of continuous (violin plots, scatterplots, histograms, dot plots, dot-and-whisker plots) or categorical
    (pie and bar charts) data. Currently, it supports only the most common types of statistical tests: parametric, nonparametric, robust, and Bayesian versions of t-test/ANOVA, correlation analyses, contingency table analysis, meta-analysis, and regression analyses."
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
