travis:
  secure:
    BINSTAR_TOKEN: lA3b1KWIZBCr+04T1tiW7fL8V62MB4rFFf7Q9hCznwx6+N8sfNhyVRhR4jyI8yYMbI0ueuZuVQNeXTK/Pho/80ryTh6FrC7hnPzD3McrwMntaTsgaaEcPs6Nce5wrcB/yT8euvbP3KKpxrXF3CtZ3x7MO4Jtw5rTP2GLVl0eFxbv89RoS8W7d79K4jbcn8VZT+EgT4ScTC8Q4HYKUzAseOOAXpTheCReZHifjyuCXRbKTGGcTY8U2L23DUYEn9+9ostWdfgJeQLIucTSVSN7MpuA+9pEHWbIYPSyrV4TiUTWYgRelu0bozmXPTD8vKW3S1rjSziBiZnzzlacJblNa3oGNUNUzfGAYA9cihKE00U7BCq0UMl9iMUA2rbhSHnI6LRMROmCGke4cJmc761ipaT8QDeAHHai77CMEunPu9MQhkRWO4wHplS+fV00tPSSjZfKnDbF6yfeOMReewgwUprB4E2BqSNyKF9L4aD6Hbw91G5xHtx5Ad8oGaU/BG4KURlbDTaV2hnuaX4Ez0P18+C0RiYPyXzK5H2xwlOqTmEWsD77xLSbTR/WNEnJRe6sQeEEi8ccoxnaj/8ZCrVaAUuM+egFgq0Ngu5aLdC+mbQzpEbAdhuxK+//kdGF8o+r9ePb75eV/Kp4WqlZ74/okLxUxA3wmMuiCx51bR8CMZ4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
